### PR TITLE
Adds ReferenceTreeList with tests to Roosa

### PR DESCRIPTION
**Pull request by ifosch**

### CODE REVIEW

**Comment by ifosch** [comment]
[B] Tests is not correct!

**Comment by miguelbernadi** [comment]
Why leave roosa.go with only one line? Shouldn't it be removed from repo?

**Comment by miguelbernadi** [comment]
+1

**Comment by ifosch** [comment]
@miguelbernadi Yes, the file could be removed. I was simply considering about moving code from `main.go` there... Removing it now, meanwhile.

**Pull request merged**
