### PR TITLE
Move snapshot example to snapshot_list_test.go

### PR DESCRIPTION
**Pull request by ifosch**
**WARNING**: Needs rebase, just CR the 446cfbf commit.

This just puts the example Snapshot code in another file.

Refs [DVX-5662](https://mydevex.atlassian.net/browse/DVX-5662)

### CODE REVIEW

**Comment by christofdamian** [comment]
+1

**Comment by dsager** [comment]
+1

**Comment by dsager** [comment]
~~[B]~~ blocking this for the rebase then!? let me know if I got you wrong...

**Comment by ifosch** [comment]
@dsager rebase done, the block is not needed anymore, thanks!

**Pull request merged**
