### PR TITLE
Find which Security Groups have a certian IP in their rules

### PR DESCRIPTION
**Pull request by miguelbernadi**
This PR adds the ability to retrieve a list of Security Group Ids which contain a specific CIDR in one of their rules.

### CODE REVIEW

**Comment by nicolas-fricke** [comment]
Sorry, I don't really feel able to review this 🙈

**Comment by miguelbernadi** [comment]
@nicolas-fricke no problem. It's a bit complicated this one.

**Comment by christofdamian** [comment]
+1

**Comment by ifosch** [comment]
+1

**Pull request merged**
