### PR TITLE
Wire instance create command to separated code

### PR DESCRIPTION
**Pull request by ifosch**

### CODE REVIEW

**Comment by ifosch** [comment]
Beloved github.com, please, take a look, since Mr. Travis passed the tests... some time ago....
or retest this

**Comment by dsager** [comment]
+1

**Comment by ifosch** [comment]
retest this

**Comment by christofdamian** [comment]
+1

**Comment by ifosch** [comment]
retest this

**Comment by ifosch** [comment]
retest this

**Comment by ifosch** [comment]
retest this

**Comment by ifosch** [comment]
retest this

**Pull request merged**
