### PR TITLE
DVX-5412: Add tool to create entries for healthchecks

### PR DESCRIPTION
**Pull request by miguelbernadi**
Create a tool to add healthcheck entries when creating new crons. Output is designed to be parsable by scripts to automate creation of cron_entry recipes.

### CODE REVIEW

**Comment by christofdamian** [comment]
+1

**Comment by dsager** [comment]
+1
but no idea if this all makes sense, tbh :)

**Comment by miguelbernadi** [comment]
@dsager What's your concern? We can discuss it as much as needed.

**Comment by dsager** [comment]
no concern, I just wanted to point out that my +1 isn't worth much, since I don't know much about go nor about the used libs...

**Pull request merged**
