### PR TITLE
Updating README

### PR DESCRIPTION
**Pull request by ifosch**
This is intended as a change to merge to test auto-merge.

### CODE REVIEW

**Review by eporter82 — APPROVED** [review]

**Comment by dsager** [comment]
+1

**Comment by ifosch** [comment]
> +1

This repo is now using automerge ;)

**Comment by dsager** [comment]
> This repo is now using automerge ;)

But how does the repo use the workflow if we're only adding it in this PR :thinking:

**Review by dsager — APPROVED** [review]

**Comment by ifosch** [comment]
> > This repo is now using automerge ;)
> 
> But how does the repo use the workflow if we're only adding it in this PR 🤔

YMMV, but in my experience both Jenkinsfiles and GH workflows are applied from the source branch. I've always felt this was wrong and trouble, but I got used to that.

**Comment by dsager** [comment]
> YMMV, but in my experience both Jenkinsfiles and GH workflows are applied from the source branch. I've always felt this was wrong and trouble, but I got used to that.

Weird, I thought that workflow files from the source branch weren't allowed. I ran into some errors related to this. Maybe it depends on the repo setting?!

**Pull request merged**
