### PR TITLE
DVX-5064: Makes GetCreateDBInstanceInput a method of CreateDBParams

### PR DESCRIPTION
**Pull request by ifosch**

### CODE REVIEW

**Comment by miguelbernadi** [comment]
+1

**Comment by ifosch** [comment]
[B] To add the error handling appropriately

**Comment by ifosch** [comment]
@miguelbernadi I changed the error handling

**Comment by miguelbernadi** [comment]
still the same

**Comment by towanda** [comment]
+!

**Comment by towanda** [comment]
+1

**Pull request merged**
